# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7aa6b2627bdc94b6c8505063a348adc4922b1020c1a5bd9ec1e714fab0bdcb6ed7b46095f514718592c4071a0e3f6ae66ec9498408452ca10d81fe3baa854403

test:
  secret_key_base: c96db8626c6f24f9d822a3d8b9aa995002b2e7e1f0392c17f474bb4918fff5d2d9871cd7667a9bd916cb21ad502451e523415ee57a909e69b071a490bfc12f66

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
